import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";
import { AccordionProvider } from "./accordion/AccordionContex";
import { CounterProvider} from "./counter/CounterContex";
import { TodoProvider } from "./todolist/TodoContext";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
        <TodoProvider>
          <CounterProvider>
            <AccordionProvider>
            <Navbar />
              <main>{children}</main>
            </AccordionProvider>
          </CounterProvider>
        </TodoProvider>
      </body>
    </html>
  );
}